
// Code generated by stanc v2.29.2
#include <stan/model/model_header.hpp>
namespace stan_file_notrunc_model_namespace {

using stan::model::model_base_crtp;
using namespace stan::math;


stan::math::profile_map profiles__;
static constexpr std::array<const char*, 24> locations_array__ = 
{" (found before start of program)",
 " (in '/Users/jakob/Documents/Studium/master_thesis/bayes/toyMC/stan_file_notrunc.stan', line 8, column 1 to column 12)",
 " (in '/Users/jakob/Documents/Studium/master_thesis/bayes/toyMC/stan_file_notrunc.stan', line 23, column 1 to column 17)",
 " (in '/Users/jakob/Documents/Studium/master_thesis/bayes/toyMC/stan_file_notrunc.stan', line 24, column 1 to column 19)",
 " (in '/Users/jakob/Documents/Studium/master_thesis/bayes/toyMC/stan_file_notrunc.stan', line 25, column 1 to column 14)",
 " (in '/Users/jakob/Documents/Studium/master_thesis/bayes/toyMC/stan_file_notrunc.stan', line 26, column 1 to column 37)",
 " (in '/Users/jakob/Documents/Studium/master_thesis/bayes/toyMC/stan_file_notrunc.stan', line 28, column 5 to column 53)",
 " (in '/Users/jakob/Documents/Studium/master_thesis/bayes/toyMC/stan_file_notrunc.stan', line 29, column 2 to column 40)",
 " (in '/Users/jakob/Documents/Studium/master_thesis/bayes/toyMC/stan_file_notrunc.stan', line 27, column 15 to line 30, column 2)",
 " (in '/Users/jakob/Documents/Studium/master_thesis/bayes/toyMC/stan_file_notrunc.stan', line 27, column 1 to line 30, column 2)",
 " (in '/Users/jakob/Documents/Studium/master_thesis/bayes/toyMC/stan_file_notrunc.stan', line 16, column 2 to column 68)",
 " (in '/Users/jakob/Documents/Studium/master_thesis/bayes/toyMC/stan_file_notrunc.stan', line 14, column 14 to line 17, column 2)",
 " (in '/Users/jakob/Documents/Studium/master_thesis/bayes/toyMC/stan_file_notrunc.stan', line 14, column 1 to line 17, column 2)",
 " (in '/Users/jakob/Documents/Studium/master_thesis/bayes/toyMC/stan_file_notrunc.stan', line 19, column 1 to column 21)",
 " (in '/Users/jakob/Documents/Studium/master_thesis/bayes/toyMC/stan_file_notrunc.stan', line 2, column 1 to column 16)",
 " (in '/Users/jakob/Documents/Studium/master_thesis/bayes/toyMC/stan_file_notrunc.stan', line 3, column 8 to column 9)",
 " (in '/Users/jakob/Documents/Studium/master_thesis/bayes/toyMC/stan_file_notrunc.stan', line 3, column 1 to column 15)",
 " (in '/Users/jakob/Documents/Studium/master_thesis/bayes/toyMC/stan_file_notrunc.stan', line 4, column 8 to column 9)",
 " (in '/Users/jakob/Documents/Studium/master_thesis/bayes/toyMC/stan_file_notrunc.stan', line 4, column 1 to column 16)",
 " (in '/Users/jakob/Documents/Studium/master_thesis/bayes/toyMC/stan_file_notrunc.stan', line 5, column 8 to column 9)",
 " (in '/Users/jakob/Documents/Studium/master_thesis/bayes/toyMC/stan_file_notrunc.stan', line 5, column 1 to column 17)",
 " (in '/Users/jakob/Documents/Studium/master_thesis/bayes/toyMC/stan_file_notrunc.stan', line 23, column 14 to column 15)",
 " (in '/Users/jakob/Documents/Studium/master_thesis/bayes/toyMC/stan_file_notrunc.stan', line 24, column 8 to column 9)",
 " (in '/Users/jakob/Documents/Studium/master_thesis/bayes/toyMC/stan_file_notrunc.stan', line 25, column 8 to column 9)"};




class stan_file_notrunc_model final : public model_base_crtp<stan_file_notrunc_model> {

 private:
  int n;
  Eigen::Matrix<double, -1, 1> phi__;
  Eigen::Matrix<double, -1, 1> asym__;
  Eigen::Matrix<double, -1, 1> dasym__; 
  Eigen::Map<Eigen::Matrix<double, -1, 1>> phi{nullptr, 0};
  Eigen::Map<Eigen::Matrix<double, -1, 1>> asym{nullptr, 0};
  Eigen::Map<Eigen::Matrix<double, -1, 1>> dasym{nullptr, 0};
 
 public:
  ~stan_file_notrunc_model() { }
  
  inline std::string model_name() const final { return "stan_file_notrunc_model"; }

  inline std::vector<std::string> model_compile_info() const noexcept {
    return std::vector<std::string>{"stanc_version = stanc3 v2.29.2", "stancflags = "};
  }
  
  
  stan_file_notrunc_model(stan::io::var_context& context__,
                          unsigned int random_seed__ = 0,
                          std::ostream* pstream__ = nullptr) : model_base_crtp(0) {
    int current_statement__ = 0;
    using local_scalar_t__ = double ;
    boost::ecuyer1988 base_rng__ = 
        stan::services::util::create_rng(random_seed__, 0);
    (void) base_rng__;  // suppress unused var warning
    static constexpr const char* function__ = "stan_file_notrunc_model_namespace::stan_file_notrunc_model";
    (void) function__;  // suppress unused var warning
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    (void) DUMMY_VAR__;  // suppress unused var warning
    try {
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      current_statement__ = 14;
      context__.validate_dims("data initialization","n","int",
           std::vector<size_t>{});
      n = std::numeric_limits<int>::min();
      
      
      current_statement__ = 14;
      n = context__.vals_i("n")[(1 - 1)];
      current_statement__ = 14;
      stan::math::check_greater_or_equal(function__, "n", n, 0);
      current_statement__ = 15;
      stan::math::validate_non_negative_index("phi", "n", n);
      current_statement__ = 16;
      context__.validate_dims("data initialization","phi","double",
           std::vector<size_t>{static_cast<size_t>(n)});
      phi__ = 
        Eigen::Matrix<double, -1, 1>::Constant(n,
          std::numeric_limits<double>::quiet_NaN());
      new (&phi) Eigen::Map<Eigen::Matrix<double, -1, 1>>(phi__.data(), n);
      
      {
        std::vector<local_scalar_t__> phi_flat__;
        current_statement__ = 16;
        phi_flat__ = context__.vals_r("phi");
        current_statement__ = 16;
        pos__ = 1;
        current_statement__ = 16;
        for (int sym1__ = 1; sym1__ <= n; ++sym1__) {
          current_statement__ = 16;
          stan::model::assign(phi, phi_flat__[(pos__ - 1)],
            "assigning variable phi", stan::model::index_uni(sym1__));
          current_statement__ = 16;
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 17;
      stan::math::validate_non_negative_index("asym", "n", n);
      current_statement__ = 18;
      context__.validate_dims("data initialization","asym","double",
           std::vector<size_t>{static_cast<size_t>(n)});
      asym__ = 
        Eigen::Matrix<double, -1, 1>::Constant(n,
          std::numeric_limits<double>::quiet_NaN());
      new (&asym) Eigen::Map<Eigen::Matrix<double, -1, 1>>(asym__.data(), n);
      
      {
        std::vector<local_scalar_t__> asym_flat__;
        current_statement__ = 18;
        asym_flat__ = context__.vals_r("asym");
        current_statement__ = 18;
        pos__ = 1;
        current_statement__ = 18;
        for (int sym1__ = 1; sym1__ <= n; ++sym1__) {
          current_statement__ = 18;
          stan::model::assign(asym, asym_flat__[(pos__ - 1)],
            "assigning variable asym", stan::model::index_uni(sym1__));
          current_statement__ = 18;
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 19;
      stan::math::validate_non_negative_index("dasym", "n", n);
      current_statement__ = 20;
      context__.validate_dims("data initialization","dasym","double",
           std::vector<size_t>{static_cast<size_t>(n)});
      dasym__ = 
        Eigen::Matrix<double, -1, 1>::Constant(n,
          std::numeric_limits<double>::quiet_NaN());
      new (&dasym) Eigen::Map<Eigen::Matrix<double, -1, 1>>(dasym__.data(), n);
        
      
      {
        std::vector<local_scalar_t__> dasym_flat__;
        current_statement__ = 20;
        dasym_flat__ = context__.vals_r("dasym");
        current_statement__ = 20;
        pos__ = 1;
        current_statement__ = 20;
        for (int sym1__ = 1; sym1__ <= n; ++sym1__) {
          current_statement__ = 20;
          stan::model::assign(dasym, dasym_flat__[(pos__ - 1)],
            "assigning variable dasym", stan::model::index_uni(sym1__));
          current_statement__ = 20;
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 21;
      stan::math::validate_non_negative_index("y_tilde", "n", n);
      current_statement__ = 22;
      stan::math::validate_non_negative_index("log_lik", "n", n);
      current_statement__ = 23;
      stan::math::validate_non_negative_index("mu", "n", n);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    num_params_r__ = 1;
    
  }
  
  template <bool propto__, bool jacobian__ , typename VecR, typename VecI, 
  stan::require_vector_like_t<VecR>* = nullptr, 
  stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr> 
  inline stan::scalar_type_t<VecR> log_prob_impl(VecR& params_r__,
                                                 VecI& params_i__,
                                                 std::ostream* pstream__ = nullptr) const {
    using T__ = stan::scalar_type_t<VecR>;
    using local_scalar_t__ = T__;
    T__ lp__(0.0);
    stan::math::accumulator<T__> lp_accum__;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    (void) DUMMY_VAR__;  // suppress unused var warning
    static constexpr const char* function__ = "stan_file_notrunc_model_namespace::log_prob";
    (void) function__;  // suppress unused var warning
    
    try {
      local_scalar_t__ sigma = DUMMY_VAR__;
      current_statement__ = 1;
      sigma = in__.template read<local_scalar_t__>();
      {
        current_statement__ = 12;
        for (int k = 1; k <= n; ++k) {
          current_statement__ = 10;
          lp_accum__.add(
            stan::math::normal_lpdf<propto__>(
              stan::model::rvalue(asym, "asym", stan::model::index_uni(k)),
              (sigma *
                stan::math::cos(
                  (((stan::math::pi() / 180.) * 2) *
                    (-45 -
                      stan::model::rvalue(phi, "phi",
                        stan::model::index_uni(k)))))),
              stan::model::rvalue(dasym, "dasym", stan::model::index_uni(k))));
        }
        current_statement__ = 13;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(sigma, 0, 1));
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    lp_accum__.add(lp__);
    return lp_accum__.sum();
    } // log_prob_impl() 
    
  template <typename RNG, typename VecR, typename VecI, typename VecVar, 
  stan::require_vector_like_vt<std::is_floating_point, VecR>* = nullptr, 
  stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr, 
  stan::require_std_vector_vt<std::is_floating_point, VecVar>* = nullptr> 
  inline void write_array_impl(RNG& base_rng__, VecR& params_r__,
                               VecI& params_i__, VecVar& vars__,
                               const bool emit_transformed_parameters__ = true,
                               const bool emit_generated_quantities__ = true,
                               std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    static constexpr bool propto__ = true;
    (void) propto__;
    double lp__ = 0.0;
    (void) lp__;  // dummy to suppress unused var warning
    int current_statement__ = 0; 
    stan::math::accumulator<double> lp_accum__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    constexpr bool jacobian__ = false;
    (void) DUMMY_VAR__;  // suppress unused var warning
    static constexpr const char* function__ = "stan_file_notrunc_model_namespace::write_array";
    (void) function__;  // suppress unused var warning
    
    try {
      double sigma = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 1;
      sigma = in__.template read<local_scalar_t__>();
      out__.write(sigma);
      if (stan::math::logical_negation((stan::math::primitive_value(
            emit_transformed_parameters__) || stan::math::primitive_value(
            emit_generated_quantities__)))) {
        return ;
      } 
      if (stan::math::logical_negation(emit_generated_quantities__)) {
        return ;
      } 
      std::vector<double> y_tilde =
         std::vector<double>(n, std::numeric_limits<double>::quiet_NaN());
      Eigen::Matrix<double, -1, 1> log_lik =
         Eigen::Matrix<double, -1, 1>::Constant(n,
           std::numeric_limits<double>::quiet_NaN());
      Eigen::Matrix<double, -1, 1> mu =
         Eigen::Matrix<double, -1, 1>::Constant(n,
           std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 5;
      stan::model::assign(mu,
        stan::math::multiply(sigma,
          stan::math::cos(
            stan::math::multiply(((stan::math::pi() / 180.) * 2),
              stan::math::subtract(-45, phi)))), "assigning variable mu");
      current_statement__ = 9;
      for (int k = 1; k <= n; ++k) {
        current_statement__ = 6;
        stan::model::assign(log_lik,
          stan::math::normal_lpdf<false>(
            stan::model::rvalue(asym, "asym", stan::model::index_uni(k)),
            stan::model::rvalue(mu, "mu", stan::model::index_uni(k)),
            stan::model::rvalue(dasym, "dasym", stan::model::index_uni(k))),
          "assigning variable log_lik", stan::model::index_uni(k));
        current_statement__ = 7;
        stan::model::assign(y_tilde,
          stan::math::normal_rng(
            stan::model::rvalue(mu, "mu", stan::model::index_uni(k)),
            stan::model::rvalue(dasym, "dasym", stan::model::index_uni(k)),
            base_rng__),
          "assigning variable y_tilde", stan::model::index_uni(k));
      }
      out__.write(y_tilde);
      out__.write(log_lik);
      out__.write(mu);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    } // write_array_impl() 
    
  template <typename VecVar, typename VecI, 
  stan::require_std_vector_t<VecVar>* = nullptr, 
  stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr> 
  inline void transform_inits_impl(VecVar& params_r__, VecI& params_i__,
                                   VecVar& vars__,
                                   std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    
    try {
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      local_scalar_t__ sigma = DUMMY_VAR__;
      sigma = in__.read<local_scalar_t__>();
      out__.write(sigma);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    } // transform_inits_impl() 
    
  inline void get_param_names(std::vector<std::string>& names__) const {
    
    names__ = std::vector<std::string>{"sigma", "y_tilde", "log_lik", "mu"};
    
    } // get_param_names() 
    
  inline void get_dims(std::vector<std::vector<size_t>>& dimss__) const {
    
    dimss__ = std::vector<std::vector<size_t>>{std::vector<size_t>{},
      std::vector<size_t>{static_cast<size_t>(n)},
      std::vector<size_t>{static_cast<size_t>(n)},
      std::vector<size_t>{static_cast<size_t>(n)}};
    
    } // get_dims() 
    
  inline void constrained_param_names(
                                      std::vector<std::string>& param_names__,
                                      bool emit_transformed_parameters__ = true,
                                      bool emit_generated_quantities__ = true) const
    final {
    
    param_names__.emplace_back(std::string() + "sigma");
    if (emit_transformed_parameters__) {
      
    }
    
    if (emit_generated_quantities__) {
      for (int sym1__ = 1; sym1__ <= n; ++sym1__) {
        {
          param_names__.emplace_back(std::string() + "y_tilde" + '.' + std::to_string(sym1__));
        } 
      }
      for (int sym1__ = 1; sym1__ <= n; ++sym1__) {
        {
          param_names__.emplace_back(std::string() + "log_lik" + '.' + std::to_string(sym1__));
        } 
      }
      for (int sym1__ = 1; sym1__ <= n; ++sym1__) {
        {
          param_names__.emplace_back(std::string() + "mu" + '.' + std::to_string(sym1__));
        } 
      }
    }
    
    } // constrained_param_names() 
    
  inline void unconstrained_param_names(
                                        std::vector<std::string>& param_names__,
                                        bool emit_transformed_parameters__ = true,
                                        bool emit_generated_quantities__ = true) const
    final {
    
    param_names__.emplace_back(std::string() + "sigma");
    if (emit_transformed_parameters__) {
      
    }
    
    if (emit_generated_quantities__) {
      for (int sym1__ = 1; sym1__ <= n; ++sym1__) {
        {
          param_names__.emplace_back(std::string() + "y_tilde" + '.' + std::to_string(sym1__));
        } 
      }
      for (int sym1__ = 1; sym1__ <= n; ++sym1__) {
        {
          param_names__.emplace_back(std::string() + "log_lik" + '.' + std::to_string(sym1__));
        } 
      }
      for (int sym1__ = 1; sym1__ <= n; ++sym1__) {
        {
          param_names__.emplace_back(std::string() + "mu" + '.' + std::to_string(sym1__));
        } 
      }
    }
    
    } // unconstrained_param_names() 
    
  inline std::string get_constrained_sizedtypes() const {
    
    return std::string("[{\"name\":\"sigma\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"y_tilde\",\"type\":{\"name\":\"array\",\"length\":" + std::to_string(n) + ",\"element_type\":{\"name\":\"real\"}},\"block\":\"generated_quantities\"},{\"name\":\"log_lik\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(n) + "},\"block\":\"generated_quantities\"},{\"name\":\"mu\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(n) + "},\"block\":\"generated_quantities\"}]");
    
    } // get_constrained_sizedtypes() 
    
  inline std::string get_unconstrained_sizedtypes() const {
    
    return std::string("[{\"name\":\"sigma\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"y_tilde\",\"type\":{\"name\":\"array\",\"length\":" + std::to_string(n) + ",\"element_type\":{\"name\":\"real\"}},\"block\":\"generated_quantities\"},{\"name\":\"log_lik\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(n) + "},\"block\":\"generated_quantities\"},{\"name\":\"mu\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(n) + "},\"block\":\"generated_quantities\"}]");
    
    } // get_unconstrained_sizedtypes() 
    
  
    // Begin method overload boilerplate
    template <typename RNG>
    inline void write_array(RNG& base_rng,
                            Eigen::Matrix<double,Eigen::Dynamic,1>& params_r,
                            Eigen::Matrix<double,Eigen::Dynamic,1>& vars,
                            const bool emit_transformed_parameters = true,
                            const bool emit_generated_quantities = true,
                            std::ostream* pstream = nullptr) const {
      const size_t num_params__ = 1;
      const size_t num_transformed = 0;
      const size_t num_gen_quantities = 
  ((n + n) + n);
      std::vector<double> vars_vec(num_params__
       + (emit_transformed_parameters * num_transformed)
       + (emit_generated_quantities * num_gen_quantities));
      std::vector<int> params_i;
      write_array_impl(base_rng, params_r, params_i, vars_vec,
          emit_transformed_parameters, emit_generated_quantities, pstream);
      vars = Eigen::Map<Eigen::Matrix<double,Eigen::Dynamic,1>>(
        vars_vec.data(), vars_vec.size());
    }

    template <typename RNG>
    inline void write_array(RNG& base_rng, std::vector<double>& params_r,
                            std::vector<int>& params_i,
                            std::vector<double>& vars,
                            bool emit_transformed_parameters = true,
                            bool emit_generated_quantities = true,
                            std::ostream* pstream = nullptr) const {
      const size_t num_params__ = 1;
      const size_t num_transformed = 0;
      const size_t num_gen_quantities = 
  ((n + n) + n);
      vars.resize(num_params__
        + (emit_transformed_parameters * num_transformed)
        + (emit_generated_quantities * num_gen_quantities));
      write_array_impl(base_rng, params_r, params_i, vars, emit_transformed_parameters, emit_generated_quantities, pstream);
    }

    template <bool propto__, bool jacobian__, typename T_>
    inline T_ log_prob(Eigen::Matrix<T_,Eigen::Dynamic,1>& params_r,
                       std::ostream* pstream = nullptr) const {
      Eigen::Matrix<int, -1, 1> params_i;
      return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
    }

    template <bool propto__, bool jacobian__, typename T__>
    inline T__ log_prob(std::vector<T__>& params_r,
                        std::vector<int>& params_i,
                        std::ostream* pstream = nullptr) const {
      return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
    }


    inline void transform_inits(const stan::io::var_context& context,
                         Eigen::Matrix<double, Eigen::Dynamic, 1>& params_r,
                         std::ostream* pstream = nullptr) const final {
      std::vector<double> params_r_vec(params_r.size());
      std::vector<int> params_i;
      transform_inits(context, params_i, params_r_vec, pstream);
      params_r = Eigen::Map<Eigen::Matrix<double,Eigen::Dynamic,1>>(
        params_r_vec.data(), params_r_vec.size());
    }

  inline void transform_inits(const stan::io::var_context& context,
                              std::vector<int>& params_i,
                              std::vector<double>& vars,
                              std::ostream* pstream__ = nullptr) const {
     constexpr std::array<const char*, 1> names__{"sigma"};
      const std::array<Eigen::Index, 1> constrain_param_sizes__{1};
      const auto num_constrained_params__ = std::accumulate(
        constrain_param_sizes__.begin(), constrain_param_sizes__.end(), 0);
    
     std::vector<double> params_r_flat__(num_constrained_params__);
     Eigen::Index size_iter__ = 0;
     Eigen::Index flat_iter__ = 0;
     for (auto&& param_name__ : names__) {
       const auto param_vec__ = context.vals_r(param_name__);
       for (Eigen::Index i = 0; i < constrain_param_sizes__[size_iter__]; ++i) {
         params_r_flat__[flat_iter__] = param_vec__[i];
         ++flat_iter__;
       }
       ++size_iter__;
     }
     vars.resize(num_params_r__);
     transform_inits_impl(params_r_flat__, params_i, vars, pstream__);
    } // transform_inits() 
    
};
}

using stan_model = stan_file_notrunc_model_namespace::stan_file_notrunc_model;

#ifndef USING_R

// Boilerplate
stan::model::model_base& new_model(
        stan::io::var_context& data_context,
        unsigned int seed,
        std::ostream* msg_stream) {
  stan_model* m = new stan_model(data_context, seed, msg_stream);
  return *m;
}

stan::math::profile_map& get_stan_profile_data() {
  return stan_file_notrunc_model_namespace::profiles__;
}

#endif


